/**
 * 26 个场景元素的配置 —— 逐字段录自原站 bundle 的 oZ 数组
 * （app.beautified.js 153,784 行起）。
 *
 * 字段含义：
 * - name        对应 scene.glb 中的网格名
 * - startAt     在烘焙相机动画（59.77s）中开始显现的时间点（秒）
 * - ground      地面块：图集贴图 / 基色 / 边缘系数 / 纵深
 * - leaves      飘落树叶：颜色 / 尺寸 / 摆动幅度 / 周期
 * - sdf         SDF 遮罩参数
 * - sceneIndex  所属画作（1~6，对应 videos/.../{1..6}.mp4）
 * - title / cta 画作标题（带标题的元素是该画作的"主纸"）
 */
export interface PaperConfig {
  name: string;
  startAt: number;
  ground: { texture: string; color: string; edges: number; depth: number };
  sdf: { min: number };
  leaves?: { color: string; size: number; amplitude: number; duration: number };
  castShadow: boolean;
  hasHole: boolean;
  hasGround: boolean;
  hasHoverEffect: boolean;
  revealType: "default" | "fade";
  transparency?: boolean;
  sceneIndex: number;
  title?: string;
  cta?: string;
}

/**
 * User-selected timing overrides for the source-authored paper reveal.
 * The source runs the same tracks for 7 / 10 / 15 seconds; keeping the
 * overrides together prevents the renderer and QA from drifting apart.
 */
export const PAPER_REVEAL_TIMING = Object.freeze({
  riseSeconds: 3,
  curveSeconds: 5,
  revealSeconds: 7,
  revealProgressMax: 15,
  edgeCatchupSeconds: 0.5,
});

export const PAPERS_CONFIG: PaperConfig[] = [
  {
    name: "tree_1",
    startAt: 0,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: -1.7, depth: 4.1 },
    sdf: { min: -0.1 },
    leaves: { color: "#ffffff", size: 1.35, amplitude: 3.07, duration: 1.02 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 1,
    title: "Dales with Cows",
    cta: "Open the landscape",
  },
  {
    name: "cow_1",
    startAt: 1.25,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.7, depth: 2.19 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 1,
  },
  {
    name: "cow_2",
    startAt: 2,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.59, depth: 2.59 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 1,
  },
  {
    name: "cow_3",
    startAt: 7,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 1.2, depth: 3.4 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 1,
  },
  {
    name: "land_back_1",
    startAt: 8.25,
    ground: { texture: "watercolor/ground/brownish_green", color: "#8ba167", edges: 1.2, depth: 7 },
    sdf: { min: -0.1 },
    leaves: { color: "#4f4f4f", size: 0.7, amplitude: 1.11, duration: 1.03 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 2,
    title: "Nidderdale Farm",
    cta: "Open the landscape",
  },
  {
    name: "walker_1",
    startAt: 7.5,
    ground: { texture: "watercolor/ground/soft_green", color: "#b8c7b1", edges: 0.7, depth: 2.9 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 2,
  },
  {
    name: "land_front_1",
    startAt: 9.25,
    ground: { texture: "watercolor/ground/brownish_green", color: "#8ba167", edges: 0.7, depth: 2.69 },
    sdf: { min: -0.1 },
    leaves: { color: "#4f4f4f", size: 0.85, amplitude: 1.11, duration: 1.03 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 2,
  },
  {
    name: "land_back_2",
    startAt: 15.5,
    ground: { texture: "watercolor/ground/brown", color: "#8ba167", edges: 1.2, depth: 6 },
    sdf: { min: -0.1 },
    leaves: { color: "#efefef", size: 1.15, amplitude: 3, duration: 1.025 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 3,
    title: "North York Moors",
    cta: "Open the landscape",
  },
  {
    name: "sheep_2",
    startAt: 14,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 1.2, depth: 5 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 3,
  },
  {
    name: "sheep_1",
    startAt: 14.5,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.7, depth: 3.69 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 3,
  },
  {
    name: "land_front_2",
    startAt: 14,
    ground: { texture: "watercolor/ground/brown", color: "#8ba167", edges: 1.2, depth: 3.59 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 3,
  },
  {
    name: "land_front_4",
    startAt: 15,
    ground: { texture: "watercolor/ground/contrasted_green", color: "#8ba167", edges: 0.39, depth: 4.39 },
    sdf: { min: -0.1 },
    leaves: { color: "#a83232", size: 1.02, amplitude: 3, duration: 1.025 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 3,
  },
  {
    name: "land_back_3",
    startAt: 20,
    ground: { texture: "watercolor/ground/brownish_green", color: "#8ba167", edges: 1.2, depth: 4.2 },
    sdf: { min: -0.1 },
    leaves: { color: "#7c7c7c", size: 0.75, amplitude: 3, duration: 1.025 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 4,
    title: "Dales near Aysgarth",
    cta: "Open the landscape",
  },
  {
    name: "land_front_3",
    startAt: 22,
    ground: { texture: "watercolor/ground/brownish_green", color: "#8ba167", edges: 1.09, depth: 3.9 },
    sdf: { min: -0.1 },
    leaves: { color: "#7c7c7c", size: 0.6, amplitude: 3, duration: 1.025 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 4,
  },
  {
    name: "land_front_5",
    startAt: 23.5,
    ground: { texture: "watercolor/ground/contrasted_green", color: "#8ba167", edges: 1.2, depth: 3.4 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 4,
  },
  {
    name: "land_back_4",
    startAt: 33,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 1.2, depth: 4 },
    sdf: { min: -0.1 },
    leaves: { color: "#eb6262", size: 1.26, amplitude: 3, duration: 1.025 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 5,
    title: "Dales with Sheep",
    cta: "Open the landscape",
  },
  {
    name: "sheep_6",
    startAt: 32,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.7, depth: 2.69 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 5,
  },
  {
    name: "sheep_3",
    startAt: 32.5,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.29, depth: 2.09 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 5,
  },
  {
    name: "sheep_4",
    startAt: 31.5,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.39, depth: 2.59 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 5,
  },
  {
    name: "sheep_5",
    startAt: 33.5,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.39, depth: 3 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 5,
  },
  {
    name: "sheep_7",
    startAt: 34,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.7, depth: 3 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 5,
  },
  {
    name: "land_back_5",
    startAt: 16,
    hasHole: false,
    hasGround: false,
    castShadow: false,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.7, depth: 3 },
    sdf: { min: -0.1 },
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 6,
  },
  {
    name: "land_front_6",
    startAt: 39,
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    ground: { texture: "watercolor/ground/contrasted_green", color: "#8ba167", edges: 0.7, depth: 7 },
    leaves: { color: "#E5C459", size: 1.15, amplitude: 3, duration: 1.025 },
    sdf: { min: -0.1 },
    revealType: "default",
    sceneIndex: 6,
  },
  {
    name: "land_front_7",
    startAt: 39.5,
    castShadow: true,
    hasHole: true,
    hasGround: true,
    hasHoverEffect: true,
    ground: { texture: "watercolor/ground/brownish_green", color: "#8ba167", edges: 0.7, depth: 7.5 },
    leaves: { color: "#A6502A", size: 1.15, amplitude: 3, duration: 1.025 },
    sdf: { min: -0.1 },
    revealType: "default",
    sceneIndex: 6,
    title: "Ribblehead Viaduct",
    cta: "Open the landscape",
  },
  {
    name: "background_2",
    startAt: 40,
    revealType: "fade",
    transparency: true,
    hasHole: false,
    hasGround: false,
    castShadow: false,
    ground: { texture: "watercolor/ground/soft_green", color: "#8ba167", edges: 0.7, depth: 3 },
    sdf: { min: -0.1 },
    hasHoverEffect: true,
    sceneIndex: 6,
  },
  {
    name: "viaduc_1",
    startAt: 40.5,
    hasGround: false,
    ground: { texture: "watercolor/ground/soft_green", color: "#93aa5f", edges: 0.7, depth: 6 },
    sdf: { min: -0.1 },
    castShadow: true,
    hasHole: true,
    hasHoverEffect: true,
    revealType: "default",
    sceneIndex: 6,
  },
];

/** 地面贴图在 ktx2 图集中的坐标（原站 v1 常量，160,032 行） */
export const GROUND_ATLAS = [
  { name: "watercolor/ground/bright_green", offset: { x: 0.00048828125, y: 0.00048828125 }, size: { x: 0.3515625, y: 0.19775390625 } },
  { name: "watercolor/ground/brown", offset: { x: 0.00048828125, y: 0.19921875 }, size: { x: 0.3515625, y: 0.19775390625 } },
  { name: "watercolor/ground/brownish_green", offset: { x: 0.00048828125, y: 0.39794921875 }, size: { x: 0.3515625, y: 0.19775390625 } },
  { name: "watercolor/ground/contrasted_green", offset: { x: 0.00048828125, y: 0.5966796875 }, size: { x: 0.3515625, y: 0.19775390625 } },
  { name: "watercolor/ground/soft_green", offset: { x: 0.00048828125, y: 0.79541015625 }, size: { x: 0.3515625, y: 0.19775390625 } },
];

/** 相机动画总时长（scene.glb 中 Camera_Action_Baked 的长度） */
export const CAMERA_ANIMATION_DURATION = 59.7667;

/** 最后一个元素显现完毕、进入权益区前的相机时间 */
export const CAMERA_SCROLL_END = 55;
